### ISSUE TITLE
Task #41014579 for MCPets v3.1.1 generated an exception

### ISSUE THREAD

**Issue by dinobossytnew** [Nocsy-Workshop/mcpets#22]
```
[19:18:42 WARN]: [MCPets] Task #41014579 for MCPets v3.1.1 generated an exception
java.lang.NullPointerException: Cannot invoke "fr.nocsy.mcpets.data.Pet.getId()" because "evolution" is null
        at fr.nocsy.mcpets.data.livingpets.PetLevel.evolveTo(PetLevel.java:213) ~[MCPets 3.1.1.jar:?]
        at fr.nocsy.mcpets.data.livingpets.PetLevel.evolve(PetLevel.java:203) ~[MCPets 3.1.1.jar:?]
        at fr.nocsy.mcpets.data.livingpets.PetLevel.levelUp(PetLevel.java:317) ~[MCPets 3.1.1.jar:?]
        at fr.nocsy.mcpets.data.livingpets.PetStats.addExperience(PetStats.java:276) ~[MCPets 3.1.1.jar:?]
        at fr.nocsy.mcpets.mythicmobs.mechanics.PetExperienceMechanic$1.run(PetExperienceMechanic.java:32) ~[MCPets 3.1.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1970]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by DexterSK** [comment]
i got something similiar

```[11:08:02 WARN]: [MCPets] Task #5218 for MCPets v4.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "com.ticxo.modelengine.api.model.ModeledEntity.getMountManager()" because "model" is null
        at fr.nocsy.mcpets.data.flags.DismountFlyPetFlag$1.run(DismountFlyPetFlag.java:54) ~[MCPets 4.0.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by AlexandreChaussard** [comment]
I think it got fixed in the end.
