### ISSUE TITLE
Error using MCPets (4.1.4) on paper 1.20.1

### ISSUE THREAD

**Issue by jooles** [Nocsy-Workshop/mcpets#35]
Hi there,

I get this error when wanting to use MCPets 4.1.4:

[12:04:37] [Server thread/ERROR]: Error occurred while enabling MCPets v4.1.4 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.ItemMeta.setItemName(java.lang.String)'
	at fr.nocsy.mcpets.data.Items.unknown(Items.java:98) ~[mcpets.jar:?]
	at fr.nocsy.mcpets.data.Items.<init>(Items.java:68) ~[mcpets.jar:?]
	at fr.nocsy.mcpets.data.Items.<clinit>(Items.java:19) ~[mcpets.jar:?]
	at fr.nocsy.mcpets.data.config.ItemsListConfig.init(ItemsListConfig.java:39) ~[mcpets.jar:?]
	at fr.nocsy.mcpets.MCPets.loadConfigs(MCPets.java:48) ~[mcpets.jar:?]
	at fr.nocsy.mcpets.MCPets.onEnable(MCPets.java:92) ~[mcpets.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:04:37] [Server thread/INFO]: [MCPets] Disabling MCPets v4.1.4
[12:04:37] [Server thread/INFO]: -=-=-=-= MCPets disable =-=-=-=-
[12:04:37] [Server thread/INFO]:           See you soon
[12:04:37] [Server thread/INFO]: -=-=-=-= -=-=-=-=-=-=- =-=-=-=-
[12:04:37] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling MCPets v4.1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/entity/EntityMountEvent
	at fr.nocsy.mcpets.MCPets.onDisable(MCPets.java:112) ~[mcpets.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.EntityMountEvent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 16 more

Is this known or anything that I do wrong?

Thank you!

Best,
Jooles

**Comment by NatchaLatte** [comment]
[04:48:49 INFO]: [MCPets] Enabling MCPets v4.1.4
[04:48:49 ERROR]: [MCPets] Failed to register events for class fr.nocsy.mcpets.listeners.VanillaDismountListener because org/bukkit/event/entity/EntityDismountEvent does not exist.
[04:48:49 ERROR]: Error occurred while enabling MCPets v4.1.4 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.ItemMeta.setItemName(java.lang.String)'
        at fr.nocsy.mcpets.data.Items.unknown(Items.java:98) ~[MCPets 4.1.4-1.21+.jar:?]
        at fr.nocsy.mcpets.data.Items.<init>(Items.java:68) ~[MCPets 4.1.4-1.21+.jar:?]
        at fr.nocsy.mcpets.data.Items.<clinit>(Items.java:19) ~[MCPets 4.1.4-1.21+.jar:?]
        at fr.nocsy.mcpets.data.config.ItemsListConfig.init(ItemsListConfig.java:39) ~[MCPets 4.1.4-1.21+.jar:?]
        at fr.nocsy.mcpets.MCPets.loadConfigs(MCPets.java:48) ~[MCPets 4.1.4-1.21+.jar:?]
        at fr.nocsy.mcpets.MCPets.onEnable(MCPets.java:92) ~[MCPets 4.1.4-1.21+.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[04:48:49 INFO]: [MCPets] Disabling MCPets v4.1.4
[04:48:49 INFO]: -=-=-=-= MCPets disable =-=-=-=-
[04:48:49 INFO]:           See you soon
[04:48:49 INFO]: -=-=-=-= -=-=-=-=-=-=- =-=-=-=-
[04:48:49 ERROR]: Error occurred (in the plugin loader) while disabling MCPets v4.1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/entity/EntityMountEvent
        at fr.nocsy.mcpets.MCPets.onDisable(MCPets.java:112) ~[MCPets 4.1.4-1.21+.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.EntityMountEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 16 more

**Comment by AlexandreChaussard** [comment]
Latest Build for MCPets 4.1.4 only work with 1.21+ as stated in the plugin's name. If the issue persists with the corresponding version for 1.21 (which is 4.1.3), please reach out on Discord.
